const express = require('express');
const { Resend } = require('resend');
const supabase = require('../utils/supabase');

const router = express.Router();

const resend = new Resend(process.env.RESEND_API_KEY);

function generateEmailHTML(analysis) {
  const { clauses, summary } = analysis;
  
  const riskBadge = (level) => {
    const colors = {
      low: '#22C55E',
      medium: '#F97316',
      high: '#EF4444',
    };
    return `<span style="background-color: ${colors[level]}; color: white; padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: bold; text-transform: uppercase;">${level}</span>`;
  };

  const clausesHtml = clauses.map(clause => `
    <div style="background-color: #F8FAFC; border-left: 4px solid ${clause.riskLevel === 'high' ? '#EF4444' : clause.riskLevel === 'medium' ? '#F97316' : '#22C55E'}; padding: 16px; margin-bottom: 16px; border-radius: 0 8px 8px 0;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
        <h3 style="margin: 0; color: #1E3A8A; font-size: 16px;">${clause.type.replace(/_/g, ' ').toUpperCase()}</h3>
        ${riskBadge(clause.riskLevel)}
      </div>
      <p style="background-color: white; padding: 12px; border-radius: 4px; font-family: monospace; font-size: 13px; color: #64748B; margin-bottom: 12px; border: 1px solid #E2E8F0;">${clause.text}</p>
      <p style="color: #0F172A; margin-bottom: 8px;"><strong>What it means:</strong> ${clause.explanation}</p>
      <p style="color: #64748B; margin: 0;"><strong>Why this matters:</strong> ${clause.whyMatters}</p>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>ClauseFlag Analysis Report</title>
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #0F172A; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="text-align: center; padding: 32px 0; border-bottom: 2px solid #1E3A8A; margin-bottom: 32px;">
        <h1 style="color: #1E3A8A; margin: 0; font-size: 28px;">⚖️ ClauseFlag</h1>
        <p style="color: #EF4444; margin: 8px 0 0 0; font-weight: 600;">Flag the risk before you sign</p>
      </div>

      <div style="background-color: #1E3A8A; color: white; padding: 24px; border-radius: 12px; margin-bottom: 32px; text-align: center;">
        <h2 style="margin: 0 0 16px 0; font-size: 20px;">Analysis Summary</h2>
        <div style="display: flex; justify-content: center; gap: 32px;">
          <div>
            <div style="font-size: 32px; font-weight: bold; color: #EF4444;">${summary.highRisk}</div>
            <div style="font-size: 14px; opacity: 0.9;">High Risk</div>
          </div>
          <div>
            <div style="font-size: 32px; font-weight: bold; color: #F97316;">${summary.mediumRisk}</div>
            <div style="font-size: 14px; opacity: 0.9;">Medium Risk</div>
          </div>
          <div>
            <div style="font-size: 32px; font-weight: bold; color: #22C55E;">${summary.lowRisk}</div>
            <div style="font-size: 14px; opacity: 0.9;">Low Risk</div>
          </div>
        </div>
        <p style="margin: 16px 0 0 0; font-size: 14px; opacity: 0.9;">Total clauses analyzed: ${summary.totalClauses}</p>
      </div>

      <h2 style="color: #1E3A8A; margin-bottom: 24px;">Flagged Clauses</h2>
      
      ${clauses.length > 0 ? clausesHtml : '<p style="text-align: center; color: #64748B; padding: 32px;">No risky clauses detected in this contract.</p>'}

      <div style="background-color: #FEF3C7; border: 1px solid #F59E0B; padding: 16px; border-radius: 8px; margin-top: 32px;">
        <p style="margin: 0; color: #92400E; font-size: 14px;">
          <strong>⚠️ Important Disclaimer:</strong> This analysis is generated by AI and is for informational purposes only. 
          It does not constitute legal advice. Always consult with a qualified attorney before signing any contract.
        </p>
      </div>

      <div style="text-align: center; padding-top: 32px; border-top: 1px solid #E2E8F0; margin-top: 32px;">
        <p style="color: #64748B; font-size: 14px; margin: 0;">
          Generated by ClauseFlag • ${new Date().toLocaleDateString()}<br>
          <a href="https://clauseflag.com" style="color: #1E3A8A;">clauseflag.com</a>
        </p>
      </div>
    </body>
    </html>
  `;
}

router.post('/send-report', async (req, res) => {
  try {
    const { analysisId, email } = req.body;

    if (!analysisId || !email) {
      return res.status(400).json({ error: 'Analysis ID and email are required' });
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ error: 'Invalid email address' });
    }

    // Get analysis from database
    const { data: analysis, error } = await supabase
      .from('analyses')
      .select('*')
      .eq('id', analysisId)
      .single();

    if (error || !analysis) {
      return res.status(404).json({ error: 'Analysis not found' });
    }

    if (analysis.status !== 'completed') {
      return res.status(400).json({ error: 'Analysis not yet complete' });
    }

    // Generate email HTML
    const html = generateEmailHTML(analysis);

    // Send email
    const { data: emailData, error: emailError } = await resend.emails.send({
      from: process.env.EMAIL_FROM || 'ClauseFlag <noreply@clauseflag.com>',
      to: email,
      subject: 'Your ClauseFlag Contract Analysis Report',
      html,
    });

    if (emailError) {
      throw emailError;
    }

    // Update analysis with user email
    await supabase
      .from('analyses')
      .update({ user_email: email })
      .eq('id', analysisId);

    res.json({
      success: true,
      message: 'Report sent successfully',
      emailId: emailData?.id,
    });

  } catch (error) {
    console.error('Email send error:', error);
    res.status(500).json({
      error: 'Failed to send email',
      message: error.message,
    });
  }
});

module.exports = router;
